### ISSUE TITLE
In footer contact us is repeated remove the one contact us and embeed the google map there.

### ISSUE THREAD

**Issue by Soumabha-Banerjee** [dakshineswarshayaklibrary/website#12]
![issue ](https://user-images.githubusercontent.com/86914531/170911043-96c389f9-99db-419b-b8d6-e54b612f1572.jpg)

**Comment by Soumabha-Banerjee** [comment]
![issue ](https://user-images.githubusercontent.com/86914531/170910994-45424a84-802f-43cf-bb60-7a34078bc6f9.jpg)

**Comment by debjitpal5040** [comment]
Okay, will do

**Comment by debjitpal5040** [comment]
<img width="1440" alt="Screenshot 2022-05-30 at 19 47 09" src="https://user-images.githubusercontent.com/76846542/171010825-4f31c3dd-d051-445c-b15b-b9d069930a7f.png">
Done for now ;but maybe needed some css improvements
