### ISSUE TITLE
Design a logo and add as favicon

### ISSUE THREAD

**Issue by debjitpal5040** [dakshineswarshayaklibrary/website#18]
Create a favicon for pur library and add that in the project. It's like a small logo of our library which will be displayed in the title bar of every webpage we visit

**Comment by debjitpal5040** [comment]
Design a logo for our library and upload that

**Comment by airlive11** [comment]
Okay

**Comment by debjitpal5040** [comment]
Keeping this issue open as there might be some chance that the logo gets updated, otherwise I will close this issue soon

**Comment by airlive11** [comment]
Ok, thanks for the update.

**Comment by debjitpal5040** [comment]
Is this lo

> ![logo](https://user-images.githubusercontent.com/76846542/171833731-e00c41f4-b1a2-44fe-92c8-5e606bc4901d.png)
> Added this as a logo cum favicon

Is this logo is final ? If not then update else close this issue

**Comment by debjitpal5040** [comment]
@airlive11 Upload and insert the final updated logo

**Comment by airlive11** [comment]
work is in progress , i will upload this very soon

**Comment by debjitpal5040** [comment]
> I was send the logo to sourav da , but he wants more update, so final touch will given by sourav da. wait for 2-3 days.

No hurries, take your time
