### ISSUE TITLE
Develop Backend in Firebase 

### ISSUE THREAD

**Issue by debjitpal5040** [dakshineswarshayaklibrary/website#20]
Use firebase to deploy the backend

**Comment by Soumabha-Banerjee** [comment]
Start the Backend work at middle or end of July

**Comment by debjitpal5040** [comment]
Yup !! milestone is given as end of august

> Start the Backend work at middle or end of July

**Comment by Lakshmi-Denre** [comment]
so....akhon backend suru hoche na!

**Comment by debjitpal5040** [comment]
> so....akhon backend suru hoche na!

Haaa, pore dekha jabe, ekhn possible na
