### ISSUE TITLE
hovering on dropdown menu on navbar not working properly

### ISSUE THREAD

**Issue by debjitpal5040** [dakshineswarshayaklibrary/website#5]
<img width="207" alt="Screenshot 2022-05-23 at 15 04 07" src="https://user-images.githubusercontent.com/76846542/169790066-608f7ed7-19fa-48ed-aca5-b15ce4596424.png">

1. Hovering is outside the limits
2. expected colour is not appearing

Probably a css bug; check the class used for this hovering in css file and fix it

**Comment by Soumabha-Banerjee** [comment]
Yes have to change the color and make the css property !important. I will do it
