### ISSUE TITLE
Improve gallery page and update corresponding images

### ISSUE THREAD

**Issue by debjitpal5040** [dakshineswarshayaklibrary/website#9]
Please provide 3 beautiful library interior images and place in Images folder

**Comment by debjitpal5040** [comment]
Place all images inside img folder first and then write in gallery.html code

**Comment by airlive11** [comment]
Okay

**Comment by debjitpal5040** [comment]
Initial gallery page has been created, update the images with relevant images and do some design improvements if needed

**Comment by airlive11** [comment]
Done

**Comment by debjitpal5040** [comment]
Okay, whenever they will provide you images of library, just upload them and insert to gallery page
